### PR TITLE
Issue #601: ODataRoute should accept an interface instead of ODataPathRouteConstraint.

### PR DESCRIPTION
**Pull request by xuzhg**
Issue #601: ODataRoute should accept an interface instead of ODataPathRouteConstraint.

### CODE REVIEW

**Comment by karunasagark** [comment]
Hi Sam, Thanks for the PR. The changes look good. 
A new public property 'RouteConstraint' is introduced. I'm wondering why public? Can this be private? Wouldn't it cause confusion with 'PathRouteConstraint' property?

**Comment by xuzhg** [comment]
@karunasagark

Yes, it's a little bit confusion. However, here's the reasons:

1. Can't delete/change the `'PathRouteConstraint` because it's public.

2. If 'RouteConstraint' is private, the developer can't get the real constraint if it is not derived from `ODataPathRouteConstraint `.

For example:

```C#
class MyRouteConstraint : IHttpRouteContraint
{}


ODataRoute route = new ODataRoute("myRoute", new MyRouteConstraint());
MyRouteConstraint constraint = route.PathRouteConstraint as MyRouteConstraint;  // constraint will be null
```

**Comment by karunasagark** [comment]
@xuzhg 

Makes sense. Thank you!

Also, would you know in what version of the assembly would this fix be available?

**Comment by xuzhg** [comment]
@karunasagark  It will be in 5.9

**Comment by xuzhg** [comment]
Merged. Thanks.

**Pull request closed without merging**
