### PR TITLE
ODataResourceDeserializer Preserves Request on ODataDeserializerContext for Nested Resource

### PR DESCRIPTION
**Pull request by pdbruno**
### Issues

*This pull request fixes issue #1828.*

### Description

*Trying to acces the readContext.Request property yields a null value when deserializing nested resources

The readContext.Request property is now being copied to the nestedReadContext*

### Checklist (Uncheck if it is not completed)

- [X] *Test cases added*
- [X] *Build and test with one-click build and test script passed*

### Additional work necessary

*No Additional work necessary.*

### CODE REVIEW

**Review by xuzhg — APPROVED** [review]
:shipit:

**Comment by xuzhg** [comment]
Make sure the test can pass.

---
In reply to: [804220690](https://github.com/OData/WebApi/pull/2445#issuecomment-804220690) [](ancestors = 804220690)

**Comment by pdbruno** [comment]
> Make sure the test can pass.
> 
> In reply to: [804220690](https://github.com/OData/WebApi/pull/2445#issuecomment-804220690) [](ancestors = 804220690)

In order for the new test to pass, the project would need additional dependencies (System.Web.Http, System.Net.Http) because of the new property being testes. Should I add those dependecies myself? If so, how can I do it?

**Comment by xuzhg** [comment]
UnitTest shared project is referenced by ".NET Classic" and ".NET Core" Unit test project.
you can open the corresponding solution, use the "nuget package manager" to install the new dependencies.

But, before including the new dependencies (most of time it's rejected to involve new dependencies), let's ask us "Can we avoid introducing new dependencies by changing the test cases"? 
Let's Keep the unit test as unique as possible.

---
In reply to: [804256211](https://github.com/OData/WebApi/pull/2445#issuecomment-804256211) [](ancestors = 804256211)

**Comment by pdbruno** [comment]
> UnitTest shared project is referenced by ".NET Classic" and ".NET Core" Unit test project.
> you can open the corresponding solution, use the "nuget package manager" to install the new dependencies.
> 
> But, before including the new dependencies (most of time it's rejected to involve new dependencies), let's ask us "Can we avoid introducing new dependencies by changing the test cases"?
> Let's Keep the unit test as unique as possible.
> 
> In reply to: [804256211](https://github.com/OData/WebApi/pull/2445#issuecomment-804256211) [](ancestors = 804256211)

Hello! Is this ready to be merged? I fixed the test

**Pull request merged**
