### PR TITLE
Fixes unit tests regarding international notation, and missing Attribute

### PR DESCRIPTION
**Pull request by egbertn**
### Issues

*This pull request fixes issue #1709.* and issue #1708.*

### Description

Two unit tests fail on a computer with non US settings.

### Checklist (Uncheck if it is not completed)

- [ ] *Test cases added*
- [ ] *Build and test with one-click build and test script passed*
AttributeRouting_TopFunctionWithEntityParameter
CalcBirthday

### Additional work necessary

None necessary. Just two tiny keywords added.

### CODE REVIEW

**Comment by xuzhg** [comment]
@egbertn feature/netcore is replaced by the master branch. Would you please port your change to master branch?

**Comment by egbertn** [comment]
Hi Sam, Sorry, you can ignore it. I tried to run all tests on the master branch, however, other unit tests fail now. Say 5 unit routing tests. The affected code that I fixed, is not there anymore.

**Comment by xuzhg** [comment]
So, Can we close it?

**Comment by egbertn** [comment]
Sure. Go ahead.

**Pull request closed without merging**
