### PR TITLE
Fix EfCore memory leak when query contains collection constant

### PR DESCRIPTION
**Pull request by habbes**
### Issues

This pull request fixes issue #2089 

### Description

EF core caches compiled queries so it doesn't have to re-compile the same query twice. The compiled queries are usually parameterized so that if the same query is made with different input values, the same cached query will be re-used. However, if a constant expression is inside a lambda, it's not parameterized, this means the same query with different values will result in queries being compiled and cache (see https://github.com/dotnet/efcore/issues/10535#issuecomment-375116203). If such queries are made frequently, then the size of the cache quickly grows over time unnecessarily (see https://dzone.com/articles/investigating-a-memory-leak-in-entity-framework-co).

WebApi has a setting `EnableConstantParameterization` which is enabled by default to prevent this issue. It uses `LinqParameterContainer.ParameterizeConstant()` to wrap the constant value in a property of a class instance and replaces the `ConstantExpression` with a `PropertyExpression`. This mimics how the compiler handles closures. This parameterization was applied to Uri Parser's `ConstantNode` but not to `CollectionConstantNode`. This PR simply applies it to `CollectionConstanNode`.

### Checklist (Uncheck if it is not completed)

- [x] *Test cases added*
- [x] *Build and test with one-click build and test script passed*

### Additional work necessary

*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

### CODE REVIEW

**Comment by habbes** [comment]
I did notice some strange behaviour related to the number of cached entries before my PR. When I flooded the server with 1000 queries, then took a snapshot of the memory (using VS's studio diagnostic tools) I would find that the number of entries in `Microsoft.Extensions.Caching.Memory.MemoryCache` has increased by about 1000 (from 2 to 1002). But when I flooded it with subsequent queries, the entries do not increase, in fact they decreased to about 964. At this point I cannot explain this behaviour, but then again I'm not very well versed with the internal mechanisms of EF Core caching and what the expected behaviour should be. After I implemented the fix, the number of entries only increase by 1 (from 2 to 3).

**Comment by xuzhg** [comment]
:thumbsup: 

---
In reply to: [632511089](https://github.com/OData/WebApi/pull/2172#issuecomment-632511089) [](ancestors = 632511089)

**Comment by xuzhg** [comment]
Looks good to me. Thanks.

---
In reply to: [417038318](https://github.com/OData/WebApi/pull/2172#issuecomment-417038318) [](ancestors = 417038318)

**Comment by xuzhg** [comment]
Merged at: 8de67a7e4e40973f3a03227863069a9ec14cbdab

**Pull request closed without merging**
