### PR TITLE
[vNext] Fix NullReferenceExceptions in DynamicPropertyRouting and OdataFeature

### PR DESCRIPTION
**Pull request by genusP**

### CODE REVIEW

**Comment by xuzhg** [comment]
Merge at: a85247179283418e092f00e085e441032230826e
Thanks your contribution.

@genusP 
vNext branch is still in development. We'd love to see more PRs from you and all other developers.

**Comment by robward-ms** [comment]
@genusP: As you and discussed earlier (see PR #942 ), we are planning to combine the code in vNext with the code in OData60 to share common code. All of the fixes in vNext will get consumed for the shared OData60/vNext version we'll release, which will first be staged to a new branch and then get merged to master.

As a result, we would not wind up releasing code from the vNext branch directly. To save it's history (but to avoid the confusion of when the code in vNext no longer represents a future version), we're planning to change the branch name to _**maintenance-aspnetcore**_. It will have the same history as **_vNext_**, and you can continue to make contributions. We hope to have the new branch available this week.

Let us know if you have any concerns.

**Comment by genusP** [comment]
OK. I would like to see the progress of work on OData60 for aspnetcore. Thank you.

**Comment by robward-ms** [comment]
Yep, our intention is to put the code in a topic branch for all to view/comment/contribute. Eventually, it will make it's way to master once we ship the RTM version. If you want to take a peek, take a look at https://github.com/robward-ms/WebApi/tree/OData60-NetCore-Step11c-AllFixes

**Comment by robward-ms** [comment]
@genusP, Just remembered that the link above only has the ASP.Net Classic side. The ASP.Net core side has been validated but not yet pushed. All you can see at the moment is the refactoring of common code.

**Comment by biaol-odata** [comment]
Hi @genusP, FYI, the vNext branch has been renamed to maintenance-aspnetcore (see @robward-ms's note above) with the updated README. Everything else inside unchanged. Thanks.

**Comment by genusP** [comment]
Thank you!

**Pull request closed without merging**
