### PR TITLE
Issue #194 Count with filter support

### LINKED ISSUE #194: Count with filter doesn't work in ODATA queries
According to ODATA v4 Spec Protocol Part 

Section 11.2.5.1 System Query Option $filter

http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398301 

The following query is supported in ODATA

http://host/service/Categories?$filter=Products/$count lt 10

However when I try this against a Web API 2.2 with OData4, I am getting the following error:

> "code":"","message":"The query specified in the URI is not valid. The parent value for a property access of a property '$count' is not a single value. Property access can only be applied to a single value.","innererror":{ "message":"The parent value for a property access of a property '$count' is not a single value. Property access can only be applied to a single value.","type":"Microsoft.OData.Core.ODataException","stacktrace":"   at Microsoft.OData.Core.UriParser.Parsers.EndPathBinder.BindEndPath....

Is this the expected behavior?

### PR DESCRIPTION
**Pull request by VikingsFan**
### Issues

This pull request fixes #194

### CODE REVIEW

**Comment by xuzhg** [comment]
Merged for 5.x at: https://github.com/OData/WebApi/commit/455173728f6d66ed0fbe842a6ca78837e4fbe437

Thanks your contribution.

**Comment by robertmclaws** [comment]
An we get this integrated got 6.X too please?

**Comment by xuzhg** [comment]
@robertmclaws ODL 7.x doesn't include the fix for $count in $filter. Once it has, I'd love to port the changes here to Web API 6.x.

**Comment by haoyang1989** [comment]
http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752351

**Pull request closed without merging**
