### PR TITLE
Migrated everything to the new .csproj project format and VS 2017

### PR DESCRIPTION
**Pull request by Cryowatt**
### Description
I've migrated everything to the new msbuild project format for netcore apps. I've also multi-targeted everything for a few different platforms. You can merge this or just use it as a base if you decide to migrate differently, I just did this to unblock myself.

### Checklist (Uncheck if it is not completed)
- [ x ] Build and test with one-click build and test script passed

### CODE REVIEW

**Comment by xuzhg** [comment]
@Cryowatt Thanks your contribution on the ASP.NET Core. Your PR is good however it is based the VS2017. It's better for us to wait for the RTM of VS2017. Is it ok for you?

**Comment by AlanWong-MS** [comment]
I agree, this is a great PR. Out of curiosity, did you use the [dotnet tool from the VS2017 .NET Core tools](https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/dotnet-migrate) to assist you with this migration?

**Comment by marcrocny** [comment]
With RTM out now, where does this PR stand?

**Comment by listepo** [comment]
+1

**Comment by xuzhg** [comment]
@Cryowatt We are appreciate your contribution. However, the PR looks out-of-date. I use the VS 2017 tool to covert the *.xproj to *.csproj. See the https://github.com/OData/WebApi/pull/978. I will close this PR. If you have any further question, please contact us or leave message below.

**Pull request closed without merging**
