### PR TITLE
[vNext] Updated to work with latest RC2

### PR DESCRIPTION
**Pull request by joshcomley**
I took @grahamehorner's RC1 fork and extended it to support the latest RC2

### CODE REVIEW

**Comment by VikingsFan** [comment]
@joshcomley thank you for your contribute! Please sign the license and rebase to vNext branch, thanks!

**Comment by joshcomley** [comment]
Hi, sorry I didn't get notified of your messages!

I have:
- Updated the OData sample to work with the very latest version of ASP.NET Core (1.0.0-rc2-16496)
- Updated the namespaces to Microsoft.AspNetCore
- Added (basic, non unit-tested) support for CORS
- Added (basic, non unit-tested) support for OData actions
- Rebased with the upstream master branch so there are no conflicts for merge

**Comment by VikingsFan** [comment]
@joshcomley please rebase to `vNext` branch :)

**Comment by xuzhg** [comment]
Thanks your input.

the vNext branch is migrated to RC2-final. 
See commit here: 2b032b1dab87866cad3319a46d648f7252f5556d. So, Have to reject this PR.

You are welcome to contribute Web API OData vNext more. We appreciate your next Pull request. Thanks.

**Pull request closed without merging**
