### PR TITLE
Fix the casing so that the project compiles under case-sensitive OS 

### PR DESCRIPTION
**Pull request by obohaciak**
Fix the casing so that the project compiles under case-sensitive OS like Linux

### Issues

*This pull request fixes issue #2469.*

### Description

*Corrects filename casing.*

### Checklist (Uncheck if it is not completed)

- [ ] *Test cases added - no test cases needed*
- [x] *Build and test with one-click build and test script passed*

### Additional work necessary

*No tests were added as there's no change in code. No docs needed.*

### CODE REVIEW

**Review by habbes — APPROVED** [review]

**Review by KenitoInc — APPROVED** [review]
LGTM

**Review by marabooy — APPROVED** [review]

**Comment by habbes** [comment]
I've found that while the file is named `NonBindingParameterConfiguration.cs`, the class itself is actually named `NonbindingParameterConfiguration` (`binding` is no capitalized). But renaming the class would be a breaking changing since it's a public class.

**Comment by KenitoInc** [comment]
> I've found that while the file is named `NonBindingParameterConfiguration.cs`, the class itself is actually named `NonbindingParameterConfiguration` (`binding` is no capitalized). But renaming the class would be a breaking changing since it's a public class.

We can ensure all files are consistent with the class names!

**Comment by obohaciak** [comment]
Fix the casing so that the project compiles under case-sensitive OS

**Comment by obohaciak** [comment]
Misclicked :)

**Comment by habbes** [comment]
@obohaciak in order to maintain consistency between the filenames and class names, maybe it would be better to rename the file instead to `NonbindingParameterConfiguration.cs` to match the class name.

**Comment by obohaciak** [comment]
@habbes I suppose you're right. Apologies, but @xuzhg was faster and the PR is already merged. I could open up another PR, but I don't want to waste your time reviewing trivial changes.

**Pull request merged**
