### PR TITLE
Permission scopes

### PR DESCRIPTION
**Pull request by habbes**
### Issues

*This pull request fixes issue #xxx.*

### Description

*Briefly describe the changes of this pull request.*

### Checklist (Uncheck if it is not completed)

- [ ] *Test cases added*
- [ ] *Build and test with one-click build and test script passed*

### Additional work necessary

*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

### CODE REVIEW

**Comment by xuzhg** [comment]
@habbes I think this part could be a very independent project?

**Comment by habbes** [comment]
> @habbes I think this part could be a very independent project?

I've migrated the feature to its own repo: https://github.com/habbes/WebApiAuthorization

I don't seem to have sufficient permissions to create the repo in this org.

**Comment by xuzhg** [comment]
> @xuzhg
> 
> > @habbes I think this part could be a very independent project?
> 
> I've migrated the feature to its own repo: https://github.com/habbes/WebApiAuthorization
> 
> I don't seem to have sufficient permissions to create the repo in this org.

@habbes I open a slot for you at: https://github.com/OData/AspNetCoreOData/tree/master/src/Microsoft.AspNetCore.OData.Authorization

Thanks this repo and let me know your thoughts.

**Comment by habbes** [comment]
> > @xuzhg
> > > @habbes I think this part could be a very independent project?
> > 
> > 
> > I've migrated the feature to its own repo: https://github.com/habbes/WebApiAuthorization
> > I don't seem to have sufficient permissions to create the repo in this org.
> 
> @habbes I open a slot for you at: https://github.com/OData/AspNetCoreOData/tree/master/src/Microsoft.AspNetCore.OData.Authorization
> 
> Thanks this repo and let me know your thoughts.

@xuzhg I've created a PR https://github.com/OData/AspNetCoreOData/pull/1 to migrate the project to this repo, and also moved it to the namespace `Microsoft.AspNetCore.OData.Authorization`

**Comment by xuzhg** [comment]
> > > @xuzhg
> > > > @habbes I think this part could be a very independent project?
> > > 
> > > 
> > > I've migrated the feature to its own repo: https://github.com/habbes/WebApiAuthorization
> > > I don't seem to have sufficient permissions to create the repo in this org.
> > 
> > 
> > @habbes I open a slot for you at: https://github.com/OData/AspNetCoreOData/tree/master/src/Microsoft.AspNetCore.OData.Authorization
> > Thanks this repo and let me know your thoughts.
> 
> @xuzhg I've created a PR [OData/AspNetCoreOData#1](https://github.com/OData/AspNetCoreOData/pull/1) to migrate the project to this repo, and also moved it to the namespace `Microsoft.AspNetCore.OData.Authorization`

I merged it so we can continue on the design and implementation. Since Mike is out this week, can we book some time next week to review your part?

**Comment by habbes** [comment]
This feature has been migrated to https://github.com/OData/WebApiAuthorization.

**Comment by habbes** [comment]
This feature has been migrated to the repo https://github.com/OData/WebApiAuthorization, PR: https://github.com/OData/WebApiAuthorization/pull/1

**Pull request closed without merging**
