### PR TITLE
[vNext] Issue #531 - Support for count

### PR DESCRIPTION
**Pull request by EvanMachusak**
https://github.com/OData/WebApi/issues/531

### CODE REVIEW

**Comment by xuzhg** [comment]
@EvanMachusak would you please rebase your PR based on the latest codes? Thanks

**Comment by EvanMachusak** [comment]
@xuzhg I'm sorry, I've never used git before and I have no idea what I'm doing.

**Comment by lewischeng-ms** [comment]
@EvanMachusak Don't worry, I can pick up your effective commit and apply it to the branch.

**Comment by lewischeng-ms** [comment]
Merged as https://github.com/OData/WebApi/commit/4d82a141f841b3da0e44f32ba206ea7a285c10a9. Thanks.

**Pull request closed without merging**
