### PR TITLE
Issue 578 Throw ODataException if $top or $skip overflows

### PR DESCRIPTION
**Pull request by tvdburgt**
### Issues
*This pull request fixes issue #578.*  

### Description
*Briefly describe the changes of this pull request.*

### Checklist (Uncheck if it is not completed)
- [ x ] Test cases added
- [ x ] Build and test with one-click build and test script passed

### Additional work necessary
*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

### CODE REVIEW

**Comment by VikingsFan** [comment]
@tvdburgt thanks for your contribution! can we use error string SRResources.SkipTopLimitExceeded instead of a new one?

**Comment by tvdburgt** [comment]
@VikingsFan sure, but this message requires `validationSettings.MaxSkip` as argument, but this value is not known inside the `Value` accessor.

**Comment by VikingsFan** [comment]
@tvdburgt can we use int.maxValue? as the value exceed the limit of integer.

**Comment by tvdburgt** [comment]
@VikingsFan done

**Comment by VikingsFan** [comment]
Merged 368278e40296e87a420f1bbffef038c3c4a852d2

**Pull request closed without merging**
