### PR TITLE
Addressing memory leak in ModelContainer

### PR DESCRIPTION
**Pull request by AlanWong-MS**
### Issues
#1101

### Description
Removing model container and maintaining only one Edm model structure at a time.

### Checklist (Uncheck if it is not completed)
- [x] *Test cases added*
- [ ] *Build and test with one-click build and test script passed*

### CODE REVIEW

**Comment by AlanWong-MS** [comment]
The build was using an old build definition for some reason. The build and tests pass.

**Comment by biaol-odata** [comment]
E2E tests failed. SelectExpandTests.QueryForAnEntryWithExpandNavigationPropertyExceedPageSize doesn't like a build server issue.
What is the reason for "E2E Tests except QueryForLongSelectList", "E2E Tests only QueryForLongSelectList"? Can you delete your old build def so that the PR trigger build will generate a new build def for use?

**Comment by AlanWong-MS** [comment]
Looks like the errors still persist so I'll take a look at those first. Please hold off on reviewing.

**Comment by AlanWong-MS** [comment]
Closing in favor of #1506.

**Pull request closed without merging**
