### PR TITLE
Fixes #1953. Generation of skip token value with a DateTime

### LINKED ISSUE #1953: Skiptoken cannot be generated with a DateTime value
Given the following entity CLR type
```csharp
    public class Date
    {
        [Key]
        public DateTime DateValue { get; set; }
    }
```

The skiptoken value cannot be generated and throws an exception.

### Assemblies affected

OData WebApi lib 7.6.1

### Reproduce steps
Create an OData endpoint with the following configuration:
```csharp
    public class Date
    {
        [Key]
        public DateTime DateValue { get; set; }
    }

public static IEdmModel GetEdmModel(WebRouteConfiguration configuration)
        {
            var builder = configuration.CreateConventionModelBuilder();
            builder.EntitySet<Date>("Dates");
            IEdmModel model = builder.GetEdmModel();
            return model;
        }

    public class DatesController : TestODataController
    {
        private static readonly DateTime _baseDate = new DateTime(2019, 11, 09, 0, 0, 0, DateTimeKind.Utc);
        private readonly List<Date> _dates = Enumerable.Range(0, 5).Select(i => new Date() { DateValue = _baseDate.AddSeconds(i) }).ToList();

        [EnableQuery]
        public List<Date> Get() => _dates;
    }
```
Query the endpoint `/Dates`.

### Expected result

Skiptoken is correctly generated with the value of the last record in the page.

### Actual result

Exception (resulting in HTTP 500 error):

> Microsoft.OData.ODataException: 'The type 'System.DateTime' is not supported when converting to a URI literal.'

### Additional detail

The cause is that conversion from `DateTime` of `DateTimeOffset` in not implemented in `DefaultSkipTokenHandler`

### PR DESCRIPTION
**Pull request by Galad**
### Issues

*This pull request fixes issue #1953.*

### Description

DefaultSkipTokenHandler supports CLR types using DateTime

### Checklist (Uncheck if it is not completed)

- [x] *Test cases added*
- [x] *Build and test with one-click build and test script passed*

### CODE REVIEW

**Comment by Galad** [comment]
@KanishManuja-MS 
Any chance you can tell me what the error is ?
I have trouble building master locally so I don't know what the issue is.

**Comment by Galad** [comment]
Ok, I was able to build (by installing VS 2015..) but I don't have any errors 

```
Test summary:
Passed :        24939
Skipped:        2
Failed :        0
---------------
Total : 24939
Congratulation! All of the tests passed!
Build time:     00:01:14.6736751
Test time:      00:42:30.2994902
```

**Comment by Galad** [comment]
@KanishManuja-MS Any chance you can help me on this ?

**Comment by KanishManuja-MS** [comment]
@Galad I will ensure that this gets in the next release. We are waiting on feedback for 7.3.0; 
In the meanwhile, you can inject your own SkipToken that handles date time correctly. 

Thanks for catching this and submitting a PR.

**Comment by Galad** [comment]
Thanks a lot, I will try that

**Comment by KanishManuja-MS** [comment]
@Galad https://devblogs.microsoft.com/odata/using-skiptoken-for-paging-in-asp-net-odata-and-asp-net-core-odata/
Refer to the customization part but please do continue to contribute and flag issues in the default implementation.

**Comment by xuzhg** [comment]
Merged at 7f1c284057d9831dea4f9701febea7a88fbab11a

**Pull request closed without merging**
